In [2]:
"""
Numpy
*used to do mathematical,scientific and statistical calculations.
*can handle dimensions/arrays effectively.
"""
import numpy as nu
print(nu.__version__)

2.4.2


In [3]:
arr=nu.array([1,2,3])
print(arr)

[1 2 3]


In [4]:
a=nu.array([1,2,3])
b=nu.array([4,5,6])
print(a+b)

[5 7 9]


In [5]:
arr.ndim  #no of dimensions

1

In [6]:
arr.size

3

In [7]:
arr[2]=40
arr

array([ 1,  2, 40])

In [8]:
type(arr)  #ndarray -->n-dimensional array

numpy.ndarray

In [9]:
arr*2   #can access directly

array([ 2,  4, 80])

In [10]:
#2D
arr2=nu.array([[4,5,6],[72,8,95]])
arr2

array([[ 4,  5,  6],
       [72,  8, 95]])

In [11]:
arr2.shape #row,column

(2, 3)

In [12]:
int(arr[2])

40

In [13]:
arr2[1,1].item()#[row,col]

8

In [14]:
arr3=nu.array([[[5,8,24]],[[3,66,63]],[[6,87,14]]])
arr3

array([[[ 5,  8, 24]],

       [[ 3, 66, 63]],

       [[ 6, 87, 14]]])

In [15]:
arr3[1,0,0].item() #array[block, row, column]

3

In [16]:
arr3.shape

(3, 1, 3)

In [17]:
arr3[2][0][1:]  #[1-->Slice from index 1 to the end:

array([87, 14])

In [18]:
arr3.size

9

In [19]:
arr3.reshape(1,9)

array([[ 5,  8, 24,  3, 66, 63,  6, 87, 14]])

In [27]:
print(nu.zeros(3))

[0. 0. 0.]


In [26]:
print(nu.ones(3))

[1. 1. 1.]


In [23]:
nu.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
print(nu.linspace(1,5,5))

[1. 2. 3. 4. 5.]


In [31]:
a=nu.array([30000,40000,50000])
print(a+500)
print(a*2)

[30500 40500 50500]
[ 60000  80000 100000]


In [32]:
a=nu.array([70,80,90])
print(nu.sum(a))
print(nu.mean(a))
print(nu.max(a))
print(nu.min(a))
print(nu.sqrt(a))

240
80.0
90
70
[8.36660027 8.94427191 9.48683298]


In [36]:
arr=nu.array([10,20,30,40,50])
print(arr[0])
print(arr[1:4])

10
[20 30 40]
